package com.mitm.ocr;

import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import javax.swing.filechooser.FileNameExtensionFilter;
import com.mitm.ocr.Logic.ImageRender;
import com.mitm.ocr.Logic.LoadImage;


/**
 *
 * @author account
 */
public class FileChoserForm extends javax.swing.JFrame {

    JLabel jl;

    /** Creates new form FileChoserForm */
    public FileChoserForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileNameExtensionFilter f [] = new FileNameExtensionFilter[2];
        f[0]=new FileNameExtensionFilter("JPEG", "jpg");
        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Open image file");
        setResizable(false);

        jFileChooser1.setFileFilter(f[0]);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setLabel(JLabel l) {
        jl = l;
    }

    @SuppressWarnings("static-access")
    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed

        if (evt.getActionCommand().equals("ApproveSelection")) {
            try {
                LoadImage load = new LoadImage();
                ImageRender.Img = load.loadImage(jFileChooser1.getSelectedFile());


            } catch (IOException ex) {
                System.out.println("nije ucitao sliku");
            }
            jl.setIcon(new ImageIcon(ImageRender.Img));
            setVisible(false);

        } else {
            setVisible(false);
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
